"""Tests for generator.cli_init module."""

import os
import copy
import tempfile

import pytest
import yaml

from generator.cli_init import _build_config, _save_config, _detect_existing_config, _CONFIG_PATH
from generator.config import validate_config


@pytest.fixture
def essential():
    return {"username": "testuser", "name": "Test User", "tagline": "Hello World"}


@pytest.fixture
def arms():
    return [
        {"name": "Frontend", "color": "dendrite_violet", "items": ["React", "TypeScript"]},
        {"name": "Backend", "color": "synapse_cyan", "items": ["Python", "Node.js"]},
        {"name": "DevOps", "color": "axon_amber", "items": ["Docker", "AWS"]},
    ]


@pytest.fixture
def advanced():
    return {
        "bio": "A passionate developer.",
        "company": "Acme Corp",
        "location": "Earth",
        "philosophy": "Code is art.",
        "social": {"email": "test@example.com", "linkedin": "testuser"},
        "projects": [
            {"repo": "testuser/project-a", "arm": 0, "description": "Project A"},
        ],
        "theme": {
            "void": "#080c14",
            "nebula": "#0f1623",
            "star_dust": "#1a2332",
            "synapse_cyan": "#00d4ff",
            "dendrite_violet": "#a78bfa",
            "axon_amber": "#ffb020",
            "text_bright": "#f1f5f9",
            "text_dim": "#94a3b8",
            "text_faint": "#64748b",
        },
        "stats": {"metrics": ["commits", "stars", "prs"]},
        "languages": {"exclude": ["HTML"], "max_display": 6},
    }


class TestBuildConfig:
    def test_build_config_minimal(self, essential, arms):
        config = _build_config(essential, arms, {})
        assert config["username"] == "testuser"
        assert config["profile"]["name"] == "Test User"
        assert config["profile"]["tagline"] == "Hello World"
        assert len(config["galaxy_arms"]) == 3
        assert config["galaxy_arms"][0]["name"] == "Frontend"
        assert "social" not in config
        assert "projects" not in config
        assert "theme" not in config

    def test_build_config_full(self, essential, arms, advanced):
        config = _build_config(essential, arms, advanced)
        assert config["username"] == "testuser"
        assert config["profile"]["bio"] == "A passionate developer."
        assert config["profile"]["company"] == "Acme Corp"
        assert config["profile"]["location"] == "Earth"
        assert config["profile"]["philosophy"] == "Code is art."
        assert config["social"]["email"] == "test@example.com"
        assert len(config["projects"]) == 1
        assert config["theme"]["void"] == "#080c14"
        assert config["stats"]["metrics"] == ["commits", "stars", "prs"]
        assert config["languages"]["exclude"] == ["HTML"]
        assert config["languages"]["max_display"] == 6


class TestSaveConfig:
    def test_save_config_creates_file(self, essential, arms, monkeypatch):
        config = _build_config(essential, arms, {})
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = os.path.join(tmpdir, "config.yml")
            monkeypatch.setattr("generator.cli_init._CONFIG_PATH", tmp_path)

            result_path = _save_config(config)
            assert os.path.isfile(result_path)

            with open(result_path, "r") as f:
                content = f.read()
            assert "Generated by: python -m generator.main init" in content

            loaded = yaml.safe_load(content)
            assert loaded["username"] == "testuser"
            assert loaded["profile"]["name"] == "Test User"
            assert len(loaded["galaxy_arms"]) == 3


class TestDetectExistingConfig:
    def test_detect_existing_config_found(self, monkeypatch):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = os.path.join(tmpdir, "config.yml")
            with open(tmp_path, "w") as f:
                yaml.dump({"username": "existing"}, f)

            monkeypatch.setattr("generator.cli_init._CONFIG_PATH", tmp_path)
            result = _detect_existing_config()
            assert result is not None
            assert result["username"] == "existing"

    def test_detect_existing_config_not_found(self, monkeypatch):
        monkeypatch.setattr(
            "generator.cli_init._CONFIG_PATH",
            "/nonexistent/path/config.yml",
        )
        result = _detect_existing_config()
        assert result is None


class TestConfigValidation:
    def test_config_passes_validation(self, essential, arms):
        config = _build_config(essential, arms, {})
        validated = validate_config(copy.deepcopy(config))
        assert validated["username"] == "testuser"
        assert validated["profile"]["name"] == "Test User"

    def test_full_config_passes_validation(self, essential, arms, advanced):
        config = _build_config(essential, arms, advanced)
        validated = validate_config(copy.deepcopy(config))
        assert validated["username"] == "testuser"
        assert validated["theme"]["void"] == "#080c14"
        assert validated["stats"]["metrics"] == ["commits", "stars", "prs"]
